### ISSUE TITLE
figure out a way to externalize common parts of html files such as favicon descriptions, fonts, analytics tags etc.

### ISSUE THREAD

**Issue by gunalmel** [michr-cri/redux-sample#3]

**Comment by michr-cri** [comment]
Used https://github.com/jantimon/html-webpack-plugin/blob/master/examples/custom-template/template.html as an example to be able to include html pages in an html page for the purposes of specifying footer and header sections of a page in separate files.

**Comment by michr-cri** [comment]
Same html include(templating using html-loader) could be utilized to insert js tags such as the case for google analytics.
